repositories:
    locale:
        parameters:
            dstype: mysql
            database_host: localhost
            database_port: null
            database_name: test
            database_user: root
            database_password: null
        jasperParameters:
            #abc: 123
        folder: ./myjaspers
    remoto:
        parameters:
            dstype: mysql
            database_host: localhost
            database_port: null
            database_name: test
            database_user: root
            database_password: null
        jasperParameters:
        folder: ./myjaspers
    TEST_AFI:
        parameters:
            dstype: mysql
            database_host: 172.16.1.11
            database_port: null
            database_name: TEST_AFI
            database_user: agafi
            database_password: agafi
        folder: /home/francesco/Lavoro/agenziaafi/afi/stampe
        


jasperStarterFolder: /opt/jasperstarter
port: 8777
historySize: 100
tmpFolder:
    path: /tmp/pdftmp
    deleteTmpFilesOlder: 1
    deletableExtensions: [pdf]